swagger: '2.0'
info:
  title: my-api optional-string
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello-world:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://us-central1-challenge1-310911.cloudfunctions.net/app/hello-world
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /api/read/:id:
     get:
      summary: reads the count
      operationId: count
      x-google-backend:
        address: https://us-central1-challenge1-310911.cloudfunctions.net/app/api/read/views
      responses:
        '200':
          description: A successful response
          schema:
            type: string